spring:
  application:
    name: cliente-pet

  datasource:
    url: jdbc:h2:mem:clientepetdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  servlet:
    context-path: /cliente-pet/api